project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # # D1.3 add flatpages
    path('portal/', include('simpleapp.urls')),

    path("accounts/", include("allauth.urls")),  # Оставили только allauth
    path("accounts/", include("accounts.urls")),  # Добавили эту строчку

    # D5
    path('accounts/', include('django.contrib.auth.urls')),
    ]

project/simpleapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.contrib.auth.models import User
# D8.4 Кэширование на низком уровне
from django.core.cache import cache


class Article(models.Model):
    name = models.CharField(max_length=50, unique=True)  # Name = Title
    text = models.TextField()
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='articles')
    rating = models.FloatField(validators=[MinValueValidator(0.0)], default=0)
    pub_time = models.DateTimeField(auto_now_add=True)
    # edit_time = models.DateTimeField(null=True)

    # D11.5 работа с админкой (не работает, столбец on_stock не появляется... надо прописать столбец в list_display!)
    @property
    def on_stock(self):
        return self.rating > 0

    # D6.4
    def __str__(self):
        return f'{self.name.title()}: {self.name[:10]}'

    # D8.4 Кэширование на низком уровне
    # def get_absolute_url(self):
    #     return reverse('About_article', args=[str(self.id)])
    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/portal/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'article-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

    # def __str__(self):
    #     return f'{self.name.title()}: {self.description[:20]}'
    # class Meta:
    #     verbose_name = "Статья"
    #     verbose_name_plural = "Статьи"


# Категория, к которой будет привязываться статья
class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name.title()


# D6.4. Создание списка рассылок
class Subscription(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subscriptions', )
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='subscriptions', )

project/templates/all_articles.html
{% extends 'flatpages/default.html' %}
{% block title %}Список статей{% endblock title %}
{% load custom_filters %}
{% load custom_tags %}

    <!-- D8.3 кэширование
    {% load cache %}
    {% cache 300 header %} -->


{% block content %}
<h2>Статьи</h2>
{% if perms.simpleapp.add_article %}
<h5><a href="/portal/articles/create/">Создать статью</a></h5>
{% endif %}
<hr>

{% if articles %}

<table>
    <tr>
        <td><b>Индекс</b></td>
        <td><b>Название</b></td>
        <td><b>Категория</b></td>
        <td><b>Рейтинг</b></td>
        <td><b>Текст</b></td>
        <td><b>Дата создания</b></td>
        <td><b>Время создания</b></td>
        <td></td>
        <td><b>Действия</b></td>
    </tr>

    {% for article in articles %}
    <tr>
        <td>{{ article.id }}</td>
        <td>{{ article.name }}</td>
        <td>{{ article.category.name }}</td>
        <td>{{ article.rating }}</td>
        <td>{{ article.text|truncatechars:5|truncatewords:1 }}</td>
        <td>{{ article.pub_time|date:'Y M d' }}</td>
        <td>{{ article.pub_time|date:'H m s' }}</td>
        <td><a href="/portal/{{article.id}}">Читать</a></td>
        <td>
            {% if perms.simpleapp.edit_article %}
            <a href="/portal/{{article.id}}/update"> / Редактировать</a>
            {% endif %}
        </td>
        <td>
            {% if perms.simpleapp.edit_article %}
            <a href="/portal/{{article.id}}/delete"> / Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>

<hr>

{# Страничительство #}
<h2>
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
</h2>
<!--<a href='/portal'>К списку публикаций</a>-->
<hr>


{% else %}
<h2>Статей нет.</h2>
{% endif %}

{% endblock content %}

    <!-- D8.3 кэширование
    {% endcache %} -->

project/templates/all_news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}
{% block title %}Список новостей{% endblock title %}

    <!-- D8.3 кэширование
    {% load cache %}
    {% cache 300 header %} -->

{% block content %}
<h2>Новости</h2>
{% if perms.simpleapp.add_article %}
<h5><a href="/portal/news/create/">Создать новость</a></h5>
{% endif %}
<hr>
{% if articles %}

<table>
    <tr>
        <td><b>Индекс</b></td>
        <td><b>Название</b></td>
        <td><b>Категория</b></td>
        <td><b>Рейтинг</b></td>
        <td><b>Текст</b></td>
        <td><b>Дата создания</b></td>
        <td><b>Время создания</b></td>
        <td></td>
        <td><b>Действия</b></td>
    </tr>
    {% for article in articles %}
    <tr>
        <td>{{ article.id }}</td>
        <td>{{ article.name }}</td>
        <td>{{ article.category.name }}</td>
        <td>{{ article.rating }}</td>
        <td>{{ article.text|truncatechars:5|truncatewords:1 }}</td>
        <td>{{ article.pub_time|date:'Y M d' }}</td>
        <td>{{ article.pub_time|date:'H m s' }}</td>
        <td><a href="/portal/{{article.id}}">Читать</a></td>
        <td>
            {% if perms.simpleapp.edit_article %}
            <a href="/portal/{{article.id}}/update"> / Редактировать</a>
            {% endif %}
        </td>
        <td>
            {% if perms.simpleapp.edit_article %}
            <a href="/portal/{{article.id}}/delete"> / Удалить</a>
            {% endif %}
        </td>

    </tr>
    {% endfor %}
</table>

<hr>

{# Страничительство #}
<h2>
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
</h2>
<!--<a href='/portal'>К списку публикаций</a>-->

{% else %}
<h2>Статей нет!</h2>
{% endif %}
<hr>

{% endblock content %}

    <!-- D8.3 кэширование
    {% endcache %} -->

project/templates/article.html
{% extends 'flatpages/default.html' %}
<!-- {% load custom_tags %}  -->

{% block title %}
{% endblock title %}

    <!-- D8.3 кэширование
    {% load cache %}
    {% cache 60 header %} -->

{% block content %}

<h2>
    <b>Название статьи: </b><i>{{ article.name }}</i>
    <br>
    <b>Индекс в базе: </b><i>{{ article.id }}</i>
    <br>
    <b>Категория: </b><i>{{ article.category }}</i>
    <br>
    <b>Содержание: </b><h5><i>{{ article.text }}</i></h5>
    <br>
    <b>Рейтинг: </b><i>{{ article.rating }}</i>
    <br>
    <b>Время: </b><i>{{ article.pub_time }}</i>
    <br>
    <hr>
</h2>
<h5>
    <a href='/portal'>К списку статей</a>
    {% if perms.simpleapp.edit_article %}
        <a href="{{ article.id }}/update">Редактировать</a>
    {% endif %}
    {% if perms.simpleapp.delete_article %}
        <a href="{{ article.id }}/delete">Удалить</a>
    {% endif %}

</h5>
{% endblock content %}

    <!-- D8.3 кэширование
    {% endcache %} -->

project/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создание статьи</h1>
<hr>

<form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save">
</form>
<hr>
<a href='/portal/allarticles'>К списку статей</a>
{% endblock content %}

project/templates/article_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление</h1>
<hr>
<i>id = {{ object.id }}, {{ object.name }}, {{ object.text }} {{ object.rating }}</i>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/article_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Редактирование</h1>
<hr>

<form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save">
</form>

{% endblock content %}

project/templates/articles.html
{% extends 'flatpages/default.html' %}
{% block title %}Список публикаций{% endblock title %}
{% load custom_filters %}
{% load custom_tags %}
    <!-- D8.3 кэширование
    {% load cache %}
    {% cache 60 header %} -->

{% block content %}
User id = {{ user.id }} (
{% if user.id == 1 %}
Administrator
{% else %}
{{user}}
{% endif %}
)
<br>
<h6>
    <b>Вам доступно: читать
        {% if perms.simpleapp.add_article %}
        , создавать
        {% endif %}
        {% if perms.simpleapp.edit_article %}
        , редактировать
        {% endif %}
        {% if perms.simpleapp.delete_article %}
        , удалять
        {% endif %}
публикации
</b>
    </h6>
<h2>Все публикации
<!-- <h4><i>{% if articles|length > 1%}
    (всего {{ articles.count }} )
    {% else %}
    (одна)
    {% endif %}</i></h4> -->
</h2>


<h5>
    {% if perms.simpleapp.add_article %}
    <a href="articles/create/">Создать статью</a>
    <a href="news/create/">Создать новость</a>
    {% endif %}
</h5>

<hr>
<h3> {{ empty|default_if_none:"Переменная empty пока пуста." }} </h3>

{% if articles %}
<table>
    <tr>
        <td><b>Индекс</b></td>
        <td><b>Название</b></td>
        <td><b>Категория</b></td>
        <td><b>Рейтинг</b></td>
        <td><b>Текст</b></td>
        <td><b>Время создания</b></td>
        <td><b>Действия</b></td>
    </tr>
    {% for article in articles %}
    <tr>
        <td>{{ article.id }}</td>
        <td>{{ article.name }}</td>
        <td>{{ article.category.name }}</td>
        <td>{{ article.rating }}</td>
        <td>{{ article.text|truncatechars:5|truncatewords:1 }}</td>
        <td>{{ article.pub_time|date:'Y M d H m s' }}</td>
        <td><a href="{{article.id}}">читать</a></td>
        <!-- <td>{{ time_now|date:'Y M d l' }}</td> -->
    </tr>
    {% endfor %}
</table>
<hr>

<h2>
    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
</h2>

<hr>
<!-- <i><h6>{{ articles }}</h6></i> -->
{% else %}
<h2>Ничего нет.</h2>
{% endif %}

{% endblock content %}

    <!-- D8.3 кэширование
    {% endcache %} -->

project/templates/best_article.html
{% extends 'flatpages/default.html' %}

<!-- {% load custom_tags %}
{% load custom_filters %}  -->


{% block title %}
Article
{% endblock title %}

{% block content %}
<h3>Описание лучшей публикации</h3>
<hr>
<br>
<h5>
    <table valign="down">
        <tr>
            <td>Название (цензурировано):</td>
            <td>{{ article.name|censor }}</td>
        </tr>
        <tr>
            <td>Индекс в базе:</td>
            <td><i>{{ article.id }}</i></td>
        </tr>
        <tr>
            <td>Категория:</td>
            <td>{{ article.category }}</td>
        </tr>
                <tr>
            <td>Рейтинг:</td>
            <td>{{ article.rating }}</td>
        </tr>
        <tr>
            <td>Время публикации:</td>
            <td>{{ article.pub_time }}</td>
        </tr>
        <tr>
            <td valign="top">Содержание (полное):</td>
            <!-- <td>{{ article.text|truncatewords:5 }} -->
            <td><h6>{{ article.text }}
                <!-- {% if user.is.authenticated %}
                {{ article.description }}
                {% else %}
                Только для авторизованных пользователей
                {% endif %} -->
                </h6>
            </td>
        </tr>
        <!--  <tr><td>Ограничения публикации</td></tr>  -->
        </tr>
        <tr>
            <td valign="top">Содержание (цензурировано):</td>
            <td>
                <h6>
                    <!-- {% load cache %}
                        {% cache 30 cens %} Кэшируем отдельный блок на 30 секунд -->
                            {{ article.text|censor }}
                        <!-- {% endcache %} -->
                </h6>
            </td>
        </tr>
    </table>
    <hr>
</h5>
<a href='/portal'>К списку публикаций</a>
{% endblock content %}

project/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создание новости</h1>
<hr>

<form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Save">
</form>
<hr>
<a href='/portal/allnews'>К списку новостей</a>
{% endblock content %}

project/templates/search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}
{% block title %}
Статьи
{% endblock title %}

{% block content %}
<h1>Поиск</h1>
<hr>

{% if articles %}
{# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
<form action="" method="get">
    {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
    {{ filterset.form.as_p }}
    {# Добавим кнопку отправки данных формы #}
    <input type="submit" value="Найти" />
</form>

<br>

<table>
    <tr>
        <!--<td><b>Индекс</b></td>-->
        <td><b>Название</b></td>
        <td><b>Категория</b></td>
        <td><b>Рейтинг</b></td>
        <td><b>Текст</b></td>
        <td><b>Дата создания</b></td>
        <td><b>Время создания</b></td>
        <td></td>
        <td><b>Действия</b></td>
    </tr>


{% for article in articles %}
    <tr>
        <!-- <td>{{ article.id }}</td> -->
        <td>{{ article.name }}</td>
        <td>{{ article.category.name }}</td>
        <td>{{ article.rating }}</td>
        <td>{{ article.text|truncatechars:5|truncatewords:1 }}</td>
        <td>{{ article.pub_time|date:'Y M d' }}</td>
        <td>{{ article.pub_time|date:'H m s' }}</td>
        <td><a href="/portal/{{article.id}}">Читать</a></td>
        <td>
            {% if perms.simpleapp.edit_article %}
            <a href="/portal/{{article.id}}/update"> / Редактировать</a>
            {% endif %}
        </td>
        <td>
            {% if perms.simpleapp.edit_article %}
            <a href="/portal/{{article.id}}/delete"> / Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </table>
<hr>

<h2>
    {# Информация о предыдущих страницах #}
    {% if page_obj.has_previous %}
    {# Для каждой ссылки пагинации указываем обработку через новый тег #}
    <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}
    {# Информация о текущей странице #}
    {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
            ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
</h2>
<hr>

{% else %}
<h2>По запросу ничего не найдено.</h2>
{% endif %}


<!--<h5><a href="/portal">К списку публикаций</a></h5>-->
{% endblock content %}

project/templates/start.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start page</title>
</head>
<body>

</body>
</html>

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

project/templates/test.html
{% extends 'flatpages/default.html' %}
<!-- {% load custom_tags %}  -->


{% block title %}
Лучшая статья
{% endblock title %}

{% block content %}

<!-- <label for="party">Enter a date and time:</label>
<input
        id="party"
        type="datetime-local"
        name="partydate"
        value="2023-07-15T18:30"
        min="2023-07-01T08:30"
        max="2023-07-30T08:30"/> -->

<form>
  <label for="party">Enter a date and time for your party booking:</label>
  <input id="party" type="datetime-local" name="partydate" />
</form>


{{party}}
{{partydate}}
<h2>
    <h5 style="color:f000ff">Test style (color)</h5>
    Test content
    <br>
    <textarea name="description" cols="80" rows="5" required id="id_description">any text</textarea>


    <form action="" method="get" >
        {{ filterset.form.non_field_errors }}
        {{ filterset.form.name__icontains.errors }}
        <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>
        <input
                id="{{ filterset.form.name__icontains.id }}"
                name="{{ filterset.form.name__icontains.name }}"
                value="{{ filterset.form.name__icontains.value }}"
                class="form-control"
        >
        <input type="submit" class="mt-3 btn-primary" value="Найти" />
    </form>


<!-- <br> - Перевод строки-->
<hr>

    <tr>
        <th><label for="id_category">Category:</label></th>
        <td>
            <select name="category" required id="id_category">
                <option value="">..пусто..</option>
                <option value="1" selected>Хозтовары</option>
                <option value="2">Подушки</option>
            </select>
        </td>
    </tr>


    <hr>

    <tr>
    <th><label for="id_name">Name:</label></th>
    <td>
      <input type="text" name="name" value="test" maxlength="50" required id="id_name">

    </td>
  </tr>





</h2>
<h5><a href='/portal'>К списку статей</a></h5>
{% endblock content %}